import { Animal } from "./animal";

export const Animals: Animal[] = [
    {
        id: 0,
        name: "Барсик",
        type: "Собака",
        color: "Черный",
        age: 2,
        gender: "Мальчик",
    },
    {
        id: 1,
        name: "Ева",
        type: "Кошка",
        color: "Серый",
        age: 10,
        gender: "Девочка",
    },
    {
        id: 2,
        name: "Мухтар",
        type: "Собака",
        color: "Коричневый",
        age: 3,
        gender: "Мальчик",
    },
    {
        id: 3,
        name: "Герда",
        type: "Собака",
        color: "Белый",
        age: 1,
        gender: "Девочка",
    },
    {
        id: 4,
        name: "Мурка",
        type: "Кошка",
        color: "Рыжий",
        age: 6,
        gender: "Девочка",
    },
    {
        id: 5,
        name: "Граф",
        type: "Собака",
        color: "Рыжая",
        age: 10,
        gender: "Мальчик",
    },
    {
        id: 6,
        name: "Платон",
        type: "Кот",
        color: "Черный",
        age: 5,
        gender: "Мальчик",
    },
];
